# Generated by Django 2.2.5 on 2020-01-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(default='download.png', upload_to='posts pics')),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('Assignment', 'Assignment'), ('Suggestion', 'Suggestion')], max_length=50)),
                ('time', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(default='download.png', upload_to='posts pics')),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('School news', 'School news'), ('General news', 'General news')], max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trending',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='TrendingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Trending')),
            ],
            options={
                'verbose_name_plural': 'News Comment',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Announcement')),
            ],
            options={
                'verbose_name_plural': 'Announcement Comment',
            },
        ),
    ]
