# Generated by Django 2.2.5 on 2020-01-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.FileField(default='download.png', upload_to='posts_pics'),
        ),
    ]
