# Generated by Django 2.2.5 on 2020-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200105_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
