# Generated by Django 2.2.5 on 2020-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200108_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='level',
            field=models.CharField(default='', max_length=10),
        ),
    ]
